name: Check code

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npm run verify:style

      - name: Check quality
        run: npm run verify:lint

      - name: Check compilation
        run: npm run verify:types
